# -*- coding: utf-8 -*-
"""email_spam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16f6EB5W46Lr-CuynmzFzuQv4-_7Vcr1S
"""

import pandas as pd

# Load dataset
df = pd.read_csv("spam.csv")

# Check column names (optional, in case of formatting issues)
print(df.columns)

# Ensure correct column names (adjust if needed)
# df = df.rename(columns={"v1": "Category", "v2": "Message"})

# Separate classes
spam_df = df[df["Category"] == "spam"]
ham_df = df[df["Category"] == "ham"]

# Randomly sample 50 from each class
spam_sample = spam_df.sample(n=50, random_state=42)
ham_sample = ham_df.sample(n=50, random_state=42)

# Combine and shuffle
sample_df = pd.concat([spam_sample, ham_sample]).sample(frac=1, random_state=42).reset_index(drop=True)

# Save to new CSV
sample_df.to_csv("sample_dataset.csv", index=False)

print("Sample dataset created: sample_dataset.csv")

# Regular expressions library for text cleaning (e.g., removing special characters, numbers)
import re

# Pandas for loading and manipulating datasets (DataFrame structure)
import pandas as pd

# Stopwords list (common words like "the", "is") from NLTK for text preprocessing
from nltk.corpus import stopwords

# TF-IDF Vectorizer converts text into numerical feature vectors based on term frequency
from sklearn.feature_extraction.text import TfidfVectorizer

# Splits the dataset into training and testing sets
from sklearn.model_selection import train_test_split

# Multinomial Naive Bayes algorithm — commonly used for text classification
from sklearn.naive_bayes import MultinomialNB

# Functions to evaluate model performance (accuracy, classification report, confusion matrix)
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Natural Language Toolkit — used here mainly to download resources (like stopwords)
import nltk

# Joblib for saving and loading trained models or transformers efficiently
import joblib

# Seaborn for visually appealing statistical plots (like heatmaps of confusion matrix)
import seaborn as sns

# Matplotlib for creating and customizing visualizations
import matplotlib.pyplot as plt

# Additional metrics to evaluate the model’s precision, recall, and F1-score
from sklearn.metrics import precision_score, recall_score, f1_score

import pandas as pd

# Load the dataset (email spam dataset with 'category' and 'message' columns)
data = pd.read_csv("sample_dataset.csv")

# Print a header for clarity
print("\n\nEmail Spam Dataset:")
print("============\n")

# Configure pandas to display ALL rows and columns
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

# Print total number of samples
print(f'Total number of samples in dataset = {len(data)}\n')

# Display ALL rows
print(data)

# Display all column names of the dataset
# This helps to understand what features are available in 'data'
data.columns

# Create a balanced sample dataset with 100 instances (50 spam, 50 ham)

# Filter the data to include only 'spam' and 'ham' categories
filtered_data = data[data['Category'].isin(['spam', 'ham'])]

# Group the filtered data by 'category' and take 50 samples from each group.
# If a category has less than 50 instances, take all available instances.
sample_data = filtered_data.groupby('Category').apply(
    lambda x: x.sample(n=min(len(x), 50), random_state=42)
)

# Reset the index of the resulting DataFrame, dropping the old index
sample_data = sample_data.reset_index(drop=True)

# Print the total number of samples in the balanced dataset
print(f'Balanced sample data count = {len(sample_data)}\n')

# Display the balanced sample dataset
display(sample_data)

# Count the number of unique categories in the balanced sample dataset
num_labels = sample_data['Category'].nunique()
print(f"Number of unique categories: {num_labels}")

# Count the number of instances for each category
label_counts = sample_data['Category'].value_counts()
print("\nNumber of instances for each category:")
print(label_counts)

sns.countplot( x = 'Category', data = sample_data );

# save sample_data as .csv file
sample_data.to_csv("sample_comments.csv", index=False)

import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# Download NLTK resources
nltk.download('stopwords')

# Load dataset
data = pd.read_csv("sample_comments.csv")

# Step 1: Drop rows with missing messages
data = data.dropna(subset=['Message'])

# Step 2: Initialize stopwords and stemmer
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

# Step 3: Define text cleaning function
def clean_text(text):
    # Lowercase
    text = text.lower()
    # Remove URLs
    text = re.sub(r'http\S+|www.\S+', '', text)
    # Remove email addresses
    text = re.sub(r'\S+@\S+', '', text)
    # Remove phone numbers
    text = re.sub(r'\b\d{5,}\b', '', text)
    # Remove special characters, punctuation, numbers
    text = re.sub(r'[^a-z\s]', '', text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    # Remove stopwords and apply stemming
    text = ' '.join([stemmer.stem(word) for word in text.split() if word not in stop_words])
    return text

# Step 4: Apply cleaning function
data['clean_message'] = data['Message'].apply(clean_text)

# Step 5: Preview cleaned data
print("Data after cleaning:")
print(data.head())

# Step 6: Save cleaned data to new CSV
data.to_csv("clean_sample_data.csv", index=False)
print("\nCleaned data saved to 'clean_sample_data.csv'")

# Display the column names of the DataFrame.
# This helps confirm that the DataFrame has the expected structure
# (for example after reordering or saving to a CSV).
data.columns

# Load cleaned email dataset (after preprocessing)
data = pd.read_csv("clean_sample_data.csv")

# Encode labels: ham=0, spam=1
data['label'] = data['Category'].map({'ham': 0, 'spam': 1})

# Separate features (X) and labels (y)
X = data['clean_message']  # use cleaned text
y = data['label']

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Print how many samples ended up in training and test sets
print(f"Number of training samples: {len(X_train)}")
print(f"Number of testing samples: {len(X_test)}")

# Display the first few training samples
print("\nSample training data:")
print(X_train.head())

# Initialize the TF-IDF Vectorizer to convert text into numerical feature vectors
# You can adjust max_features depending on your dataset size and ML model
vectorizer = TfidfVectorizer(max_features=1000)  # increased from 10 for better representation

# Fit the vectorizer on training data and transform
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("\nTF-IDF feature shape (train):", X_train_tfidf.shape)
print("TF-IDF feature shape (test):", X_test_tfidf.shape)

# Convert email text to TF-IDF features
vectorizer = TfidfVectorizer(max_features=1000)  # better for emails

vectorizer.fit(X_train)

# Transform training and test sets into TF-IDF feature matrices
X_train_tfidf = vectorizer.transform(X_train)

print("Training feature matrix shape:", X_train_tfidf.shape)

# Convert the TF-IDF sparse matrix for the training data into a dense (regular) array,
# then wrap it into a pandas DataFrame for easier viewing and manipulation.
# 'columns=vectorizer.get_feature_names_out()' names the columns after the TF-IDF terms.
X_train_tfidf_df = pd.DataFrame(
    X_train_tfidf.toarray(),                 # convert sparse matrix to dense array
    columns=vectorizer.get_feature_names_out()  # use the learned vocabulary as column names
)

# Round all TF-IDF values to 2 decimal places for cleaner display.
X_train_tfidf_df = X_train_tfidf_df.round(2)

# Print a header for clarity and then show the first 5 rows of the DataFrame.
print("\nTF-IDF Features DataFrame (2 decimal places):")

X_train_tfidf_df.head()

# Transform test emails into TF-IDF features
X_test_tfidf = vectorizer.transform(X_test)

# Convert to DataFrame (only for inspection; keep sparse for modeling large datasets)
X_test_tfidf_df = pd.DataFrame(
    X_test_tfidf.toarray(),
    columns=vectorizer.get_feature_names_out()
)

# Optional: include labels for inspection
X_test_tfidf_df['label'] = y_test.reset_index(drop=True)

print("\nTF-IDF Features DataFrame (Test Set):")
X_test_tfidf_df.head()

# Check the type of X_train_tfidf
print(type(X_train_tfidf))  # Should be <class 'scipy.sparse.csr.csr_matrix'>

# Check the shape: (number of samples, number of features)
print("Shape of X_train_tfidf:", X_train_tfidf.shape)

# Optionally, view the first 5 rows as a dense array (small datasets only)
print(X_train_tfidf.toarray()[:5])

# Check first 10 values
print(y_train.head(10))

# Check unique values
print("Unique labels in y_train:", y_train.unique())

# Optional: check type
print("Type of y_train:", type(y_train))

model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

joblib.dump(model, 'naive_bayes_model.pkl')
joblib.dump(vectorizer, 'tfidf_vectorizer.pkl')

# Load saved model and vectorizer
model = joblib.load('naive_bayes_model.pkl')
vectorizer = joblib.load('tfidf_vectorizer.pkl')

# Transform new emails and predict
new_emails = ["Congratulations! You won a $1000 prize!", "Hey, are we meeting today?"]
new_emails_clean = [clean_text(email) for email in new_emails]
new_emails_tfidf = vectorizer.transform(new_emails_clean)
predictions = model.predict(new_emails_tfidf)

print(predictions)  # 1=spam, 0=ham

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import joblib

# --- Load saved model and vectorizer (you already did this) ---
model = joblib.load('naive_bayes_model.pkl')
vectorizer = joblib.load('tfidf_vectorizer.pkl')

# --- Prepare test data ---
# Make sure X_test contains the cleaned messages (clean_message column)
X_test_clean = X_test.apply(clean_text)  # only if not cleaned yet

# Transform test data using loaded vectorizer
X_test_tfidf_loaded = vectorizer.transform(X_test_clean)

# Predict labels on test data
y_pred_loaded = model.predict(X_test_tfidf_loaded)

# --- Compute Evaluation Metrics ---
accuracy  = accuracy_score(y_test, y_pred_loaded)
precision = precision_score(y_test, y_pred_loaded, average='weighted')
recall    = recall_score(y_test, y_pred_loaded, average='weighted')
f1        = f1_score(y_test, y_pred_loaded, average='weighted')

metrics_df = pd.DataFrame({
    'Accuracy':  [accuracy],
    'Precision': [precision],
    'Recall':    [recall],
    'F1-Score':  [f1]
})

print("\nEvaluation Metrics:")
display(metrics_df)

# --- Confusion Matrix Table ---
conf_matrix = confusion_matrix(y_test, y_pred_loaded)
conf_matrix_df = pd.DataFrame(
    conf_matrix,
    index=['Actual Ham', 'Actual Spam'],
    columns=['Predicted Ham', 'Predicted Spam']
)

print("\nConfusion Matrix Table:")
display(conf_matrix_df)

# --- Plot Confusion Matrix Heatmap ---
plt.figure(figsize=(6,5))
sns.heatmap(
    conf_matrix,
    annot=True, fmt='d', cmap='Blues',
    xticklabels=['Ham', 'Spam'],
    yticklabels=['Ham', 'Spam']
)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

# Compute accuracy as a decimal
accuracy = accuracy_score(y_test, y_pred_loaded)

# Convert to percentage
accuracy_percent = accuracy * 100

print(f"Accuracy: {accuracy_percent:.2f}%")